import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { stdout } from 'node:process';
import { ARUN_BRAND, createBrand } from '../dist/createBrand.js';

/**
 * Writes the published brands — src/brands/arun.css — from their createBrand() input, using the
 * built createBrand(). Run it after a change to createBrand() or to a brand's input:
 * `pnpm --filter @arun-dev/tokens generate:brands`. A unit test fails while the published file
 * and createBrand() disagree.
 */
const HEADER =
  '/* The arun brand: generated by createBrand(ARUN_BRAND) — do not edit. Regenerate with\n' +
  '   `pnpm --filter @arun-dev/tokens generate:brands`. */\n';

const file = join(import.meta.dirname, '..', 'src', 'brands', 'arun.css');
await writeFile(file, HEADER + createBrand(ARUN_BRAND), 'utf8');
stdout.write(`wrote ${file}\n`);
