import { copyFile, mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { defineConfig } from 'tsdown';

/**
 * Single source of truth for the CSS cascade layer order and for which stylesheet
 * backs each layer. Order matters: earlier layers lose to later ones, so `reset`
 * is first and `utilities` last.
 *
 * Co-located components keep their CSS beside their source; everything is flattened
 * into dist/css/<layer>.css at build time so the published subpath exports
 * (@arun-dev/ui/css/chip, ...) stay stable regardless of where the source lives.
 */
const CSS_LAYERS = [
  { layer: 'reset', src: 'src/css/reset.css' },
  // Layout before components: a component's own styles win on an element that is both.
  { layer: 'stack', src: 'src/components/stack/stack.css' },
  { layer: 'grid', src: 'src/components/grid/grid.css' },
  { layer: 'heading', src: 'src/components/heading/heading.css' },
  { layer: 'paragraph', src: 'src/components/paragraph/paragraph.css' },
  { layer: 'chip', src: 'src/components/chip/chip.css' },
  { layer: 'card', src: 'src/components/card/card.css' },
  { layer: 'btn', src: 'src/components/button/button.css' },
  { layer: 'badge', src: 'src/components/badge/badge.css' },
  { layer: 'input', src: 'src/components/input/input.css' },
  { layer: 'otp-input', src: 'src/components/otp-input/otp-input.css' },
  { layer: 'textarea', src: 'src/components/textarea/textarea.css' },
  { layer: 'select', src: 'src/components/select/select.css' },
  { layer: 'dialog', src: 'src/components/dialog/dialog.css' },
  { layer: 'drawer', src: 'src/components/drawer/drawer.css' },
  { layer: 'popover', src: 'src/components/popover/popover.css' },
  { layer: 'menu', src: 'src/components/menu/menu.css' },
  { layer: 'menubar', src: 'src/components/menubar/menubar.css' },
  { layer: 'combobox', src: 'src/components/combobox/combobox.css' },
  { layer: 'tooltip', src: 'src/components/tooltip/tooltip.css' },
  { layer: 'hover-card', src: 'src/components/hover-card/hover-card.css' },
  { layer: 'tabs', src: 'src/components/tabs/tabs.css' },
  { layer: 'checkbox', src: 'src/components/checkbox/checkbox.css' },
  { layer: 'radio-group', src: 'src/components/radio-group/radio-group.css' },
  { layer: 'switch', src: 'src/components/switch/switch.css' },
  { layer: 'field', src: 'src/components/field/field.css' },
  { layer: 'fieldset', src: 'src/components/fieldset/fieldset.css' },
  { layer: 'link', src: 'src/components/link/link.css' },
  { layer: 'separator', src: 'src/components/separator/separator.css' },
  { layer: 'progress', src: 'src/components/progress/progress.css' },
  { layer: 'meter', src: 'src/components/meter/meter.css' },
  { layer: 'slider', src: 'src/components/slider/slider.css' },
  { layer: 'range-slider', src: 'src/components/range-slider/range-slider.css' },
  { layer: 'accordion', src: 'src/components/accordion/accordion.css' },
  { layer: 'alert', src: 'src/components/alert/alert.css' },
  { layer: 'spinner', src: 'src/components/spinner/spinner.css' },
  { layer: 'skeleton', src: 'src/components/skeleton/skeleton.css' },
  { layer: 'toast', src: 'src/components/toast/toast.css' },
  { layer: 'breadcrumb', src: 'src/components/breadcrumb/breadcrumb.css' },
  { layer: 'pagination', src: 'src/components/pagination/pagination.css' },
  { layer: 'stepper', src: 'src/components/stepper/stepper.css' },
  { layer: 'tree-view', src: 'src/components/tree-view/tree-view.css' },
  { layer: 'calendar', src: 'src/components/calendar/calendar.css' },
  { layer: 'date-picker', src: 'src/components/date-picker/date-picker.css' },
  { layer: 'table', src: 'src/components/table/table.css' },
  { layer: 'kbd', src: 'src/components/kbd/kbd.css' },
  { layer: 'toggle', src: 'src/components/toggle/toggle.css' },
  { layer: 'toolbar', src: 'src/components/toolbar/toolbar.css' },
  { layer: 'avatar', src: 'src/components/avatar/avatar.css' },
  { layer: 'metric', src: 'src/css/metric.css' },
  { layer: 'utilities', src: 'src/css/utilities.css' },
] as const;

function componentsEntrypoint(): string {
  const order = CSS_LAYERS.map(({ layer }) => layer).join(', ');
  const imports = CSS_LAYERS.map(({ layer }) => `@import './${layer}.css';`).join('\n');

  return [
    '/* Generated by tsdown — edit CSS_LAYERS in tsdown.config.ts, not this file. */',
    '/* Layer order declaration must come before any @layer blocks. */',
    `@layer ${order};`,
    '',
    imports,
    '',
  ].join('\n');
}

/**
 * React Server Components (decision 32): a module that starts with 'use client' is a client
 * boundary. The bundler drops the directive, so put it back on the built file of every source
 * module that has it. Output is per module (`unbundle`), so a server module — useRender, Card —
 * never shares a file with a client one.
 */
async function restoreUseClient() {
  const sources = await readdir('src', { recursive: true });
  await Promise.all(
    sources
      .filter((file) => /\.tsx?$/.test(file) && !file.includes('.spec.'))
      .map(async (file) => {
        if (!/^\s*(['"])use client\1/.test(await readFile(join('src', file), 'utf8'))) return;
        await Promise.all(
          ['.js', '.cjs'].map(async (extension) => {
            const built = join('dist', file.replace(/\.tsx?$/, extension));
            const code = await readFile(built, 'utf8');
            if (!/^\s*(['"])use client\1/.test(code))
              await writeFile(built, `'use client';\n${code}`);
          }),
        );
      }),
  );
}

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  // tsdown follows the tsconfig's sourceMap / declarationMap; tsup did not. The maps would
  // point at src/, which isn't published, so they stay off.
  sourcemap: false,
  dts: { sourcemap: false },
  clean: true,
  // Keep tsup's names (.js / .cjs, .d.ts / .d.cts) so the exports maps don't change.
  fixedExtension: false,
  outDir: 'dist',
  deps: { neverBundle: ['react', 'react-dom'] },
  unbundle: true,
  async onSuccess() {
    await restoreUseClient();
    // CSS is not imported by the TS source, so tsdown never sees it — ship it alongside the JS.
    await mkdir('dist/css', { recursive: true });
    await Promise.all(CSS_LAYERS.map(({ layer, src }) => copyFile(src, `dist/css/${layer}.css`)));
    await writeFile('dist/css/components.css', componentsEntrypoint(), 'utf8');
  },
});
