import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import { defineConfig } from 'tsup';

/**
 * Single source of truth for the CSS cascade layer order and for which stylesheet
 * backs each layer. Order matters: earlier layers lose to later ones, so `reset`
 * is first and `utilities` last.
 *
 * Co-located components keep their CSS beside their source; everything is flattened
 * into dist/css/<layer>.css at build time so the published subpath exports
 * (@arun-dev/ui/css/chip, ...) stay stable regardless of where the source lives.
 */
const CSS_LAYERS = [
  { layer: 'reset', src: 'src/css/reset.css' },
  { layer: 'chip', src: 'src/components/chip/chip.css' },
  { layer: 'card', src: 'src/components/card/card.css' },
  { layer: 'btn', src: 'src/components/button/button.css' },
  { layer: 'badge', src: 'src/components/badge/badge.css' },
  { layer: 'metric', src: 'src/css/metric.css' },
  { layer: 'utilities', src: 'src/css/utilities.css' },
] as const;

function componentsEntrypoint(): string {
  const order = CSS_LAYERS.map(({ layer }) => layer).join(', ');
  const imports = CSS_LAYERS.map(({ layer }) => `@import './${layer}.css';`).join('\n');

  return [
    '/* Generated by tsup — edit CSS_LAYERS in tsup.config.ts, not this file. */',
    '/* Layer order declaration must come before any @layer blocks. */',
    `@layer ${order};`,
    '',
    imports,
    '',
  ].join('\n');
}

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  outDir: 'dist',
  external: ['react', 'react-dom'],
  async onSuccess() {
    // CSS is not imported by the TS source, so tsup never sees it — ship it alongside the JS.
    await mkdir('dist/css', { recursive: true });
    await Promise.all(CSS_LAYERS.map(({ layer, src }) => copyFile(src, `dist/css/${layer}.css`)));
    await writeFile('dist/css/components.css', componentsEntrypoint(), 'utf8');
  },
});
